### PR TITLE
Publish private builds

### PR DESCRIPTION
**Pull request by sonia-y**
Allow users to publish private builds 

Reviewers:
@jinruh 
@sbaogang 
@eweizman

### CODE REVIEW

**Comment by sonia-y** [comment]
Pop up modal/dialog UI:

image

**Comment by sonia-y** [comment]
Flagged private build UI:

image

image

**Comment by sbaogang** [comment]
This is considered a Pinterest specific feature because the specific code to upload artifact to Pinterest specific repo. Can we hide this feature in the UI?

**Comment by sonia-y** [comment]
Pop up modal/dialog UI:

image

**Comment by sbaogang** [comment]
Cool, since we are not going to need the repo name etc., and already we hard coded the branch name, we could just hardcode everything and make the dialog extremely simple - just ask for SHA and file path, and we will fill out everything else.

**Comment by sonia-y** [comment]
Pop up modal/dialog UI: 

image

**Comment by sbaogang** [comment]
r+, if you can resolve the conflicts, squash all the intermediate commits before you merge.

**Pull request merged**
