### PR TITLE
spelling fixes

### PR DESCRIPTION
**Pull request by jsoref**
I didn't fix every spelling error, specifically, `actity_type` is in a database schema, and fixing that would almost certainly result in people being unhappy. -- It is possible to fix schemas, but generally that involves migration code, and coordinating with people.

I've tried to tag API change commits w/ `(API)` and `(config break)` as applicable.

I can certainly squash commits, or split the API stuff out into a distinct pull request. But until someone considers the general content, it's much better for individual fixes to be distinct -- so someone could ask me to drop a certain change.

### CODE REVIEW

**Comment by sbaogang** [comment]
Thanks for the changes, we will take a look, and if safe, probably we just do one time change.

**Comment by jsoref** [comment]
@sbaogang: anything I could do to help move this along?

**Comment by tylerwowen** [comment]
Thanks for the attempt. Close it now as it's too old.

**Comment by jsoref** [comment]
@tylerwowen fwiw, a nontrivial portion of the changes applied; that said here's a new version following the same general practices: https://github.com/pinterest/teletraan/compare/master...jsoref:pinterest-teletraan:spelling

If you're interested, I can submit a pull request. -- Note: I'm quite willing to split up such PRs -- I've been doing these PRs for many years across many orgs.

**Pull request closed without merging**
