### PR TITLE
fix the wrong help on DOW

### PR DESCRIPTION
**Pull request by sbaogang**
The previous help message is not accurate, we use quartz and the detailed doc could be found here: http://www.quartz-scheduler.org/documentation/quartz-2.x/tutorials/crontrigger.html, especially:
Day of week YES 1-7 or SUN-SAT

@haom-pinterest @lilida

### CODE REVIEW

**Comment by haom-pinterest** [comment]
Could you also make it clear the time is UTC based if it is not there?

**Comment by haom-pinterest** [comment]
I also feel that we do not have validation logic on schedule either on the UI and on the server side when it is changed because I found there were a bunch of errors in the Teletraan worker logs saying invalid schedule. This should be avoided during the interaction with users. Can be in another PR though.

**Comment by sbaogang** [comment]
right, could add validation. it is not easy to get it right.

**Comment by haom-pinterest** [comment]
r+

**Pull request merged**
