### PR TITLE
Add checkbox in cluster forms for when the cluster is managed

### PR DESCRIPTION
**Pull request by gzpcho**
image

image

image

image

image

image

### CODE REVIEW

**Comment by robbintt** [comment]
Could the checkbox go into a div appropriate with for the rest of the form contents, and maybe go in a vertical form width 
 stack above the submit button so it is much more prominent?

**Comment by robbintt** [comment]
Also I think the checkbox should have a description like "Disable Mangement", then the long language would be a tooltip or a italicized small font description on the following line?

**Comment by robbintt** [comment]
I think it would better not to ship the form partially disabled --

What do you think about:
1. ask the team if there is a straightforwards vue way to disable
- (we can sacrifice the active approach to allowing changes to the form, e.g. the checkbox would need to be submitted via the button, then the form reloads and it is editable.)
2. hide any fields that can't be disabled, so they are invisible, then solve the hiding as a followup after the project is ready.

**Comment by gzpcho** [comment]
> Could the checkbox go into a div appropriate with for the rest of the form contents, and maybe go in a vertical form width stack above the submit button so it is much more prominent?

> Also I think the checkbox should have a description like "Disable Mangement", then the long language would be a tooltip or a italicized small font description on the following line?

Addressed on [368d6ec](https://github.com/pinterest/teletraan/pull/1732/commits/368d6ec7a9768df0c7333dfb17cdbc68e112730e)

**Comment by gzpcho** [comment]
Was able to completely disable the form on [c84bb33](https://github.com/pinterest/teletraan/pull/1732/commits/c84bb332c6129413b2f8334b52a7956961ce833e)

**Review by robbintt — APPROVED** [review]

**Pull request merged**
