### PR TITLE
Teletraan UI enhancement for CMP change

### PR DESCRIPTION
**Pull request by lilida**
This is is the UI change for CMP platform. There are a number of UI changes along with Rodimus. 
@sbaogang @haom-pinterest @sjoshi6 

I have shown some of you the basic changes. Since there are too many changes, please stop by and talk to me about all the details

### CODE REVIEW

**Comment by sbaogang** [comment]
For the UI part, could you also provide screenshots to help review? Thanks!

**Comment by lilida** [comment]
Creation workflow

Click Capacity:
screen shot 2016-12-07 at 11 25 46 am

Default simple scenario for CMP
screen shot 2016-12-07 at 11 26 01 am

Advance settings
screen shot 2016-12-07 at 11 26 11 am

**Comment by lilida** [comment]
Change config workflow with NO autoscalling:
screen shot 2016-12-07 at 11 28 54 am



With autoscaling

screen shot 2016-12-07 at 11 29 12 am

**Comment by lilida** [comment]
Default Cluster Configuration Change (CMP):

screen shot 2016-12-07 at 11 30 26 am

Full cluster configuration

screen shot 2016-12-07 at 11 30 35 am

**Comment by lilida** [comment]
Add existing capacity:

screen shot 2016-12-07 at 11 31 55 am

Capacity landing page after add existing capacity:

screen shot 2016-12-07 at 11 32 59 am

**Comment by haom-pinterest** [comment]
One concern is with advanced change launch configuration setting page. It seems we expose too much and some of them should not be changed. And it is also not consistent with advanced creation setting page.

**Comment by lilida** [comment]
Replace cluster

screen shot 2016-12-07 at 11 41 26 am

Pause replacement

screen shot 2016-12-07 at 11 41 38 am

**Comment by haom-pinterest** [comment]
another potential issue might be with capacity change with autoscaling enabled. Maybe in that case, we just leave some text indicating capacity should be adjusted on autoscaling page? that is ok if we revisit this issue. minor.

**Comment by haom-pinterest** [comment]
how is replace cluster action is initiated? Did not see the related button in your screenshot.

**Comment by haom-pinterest** [comment]
what is the logic with public security group? Jayme mentioned that public security group is separate from public subnet. If a host is allocated in public subnet, it has to have a public IP assigned. We need to deal with this logic.

**Comment by lilida** [comment]
Open source version capacity settings

screen shot 2016-12-07 at 1 19 10 pm

**Comment by sbaogang** [comment]
I suggest we look at the UI tomorrow very quickly together, the screenshot
helps, but need more context.
I care less about the code, but care more about the workflow. So very first
thing tomorrow, I would like to look at the workflow in action.

**Comment by lilida** [comment]
Here is a set of new changes

Add existing appears when there is nothing set

screen shot 2016-12-08 at 6 59 29 pm


CMP Creation
screen shot 2016-12-08 at 7 07 00 pm

Advanced creation (remove cmp_group)

screen shot 2016-12-08 at 7 10 56 pm

**Comment by sbaogang** [comment]
Looks good to me, r+!

**Comment by lilida** [comment]
Capacity (Only show number state is removed)
screen shot 2016-12-09 at 11 38 11 am

Cluster config. (Replace is moved to here)
screen shot 2016-12-09 at 11 41 27 am

**Pull request merged**
