### PR TITLE
Remove all Autoscaling related code in Teletraan

### PR DESCRIPTION
**Pull request by jinruh**
@sbaogang @yujunglo @nickdechant

### CODE REVIEW

**Comment by jinruh** [comment]
Get back to what we've got 1 year ago 👍

**Comment by sbaogang** [comment]
Great, let me take a quick look

**Comment by yujunglo** [comment]
Looks good to me. Thanks for refactoring!

**Comment by nickdechant** [comment]
Looks good to me! Great work!!

**Pull request merged**
