### PR TITLE
Code updated for suggestions.

### PR DESCRIPTION
**Pull request by TheLat**

### CODE REVIEW

**Comment by yongwen** [comment]
have you tested the output for both stdout and stderr? please check with @lilida on the deployagent rollout process as well. thanks!

**Comment by yongwen** [comment]
looks good to me. requesting @lilida 's review. the rollout might be a bit complicated

**Comment by lilida** [comment]
@TheLat have you tested this on local deployment? Do you have some output  samples?

**Comment by TheLat** [comment]
I have tested this by running .sh scripts with various outputs and sleep commands based on the deploy scripts in NGAPI.  Should be good.

**Pull request merged**
