### PR TITLE
send stage type from TAS to the host and setup the environment variable

### PR DESCRIPTION
**Pull request by liyaqin1**

### CODE REVIEW

**Comment by liyaqin1** [comment]
Tested between my devapp and Teletraan dev1.
The logs look good.
TAS log:
`{"level":"INFO","logger":"com.pinterest.deployservice.handler.PingHandler","thread":"dw-24 - POST /v1/system/ping","message":"Return response com.pinterest.deployservice.bean.PingResponseBean@44ec40fe[opCode=DEPLOY,deployGoal=com.pinterest.deployservice.bean.DeployGoalBean@3fdc976a[deployId=8M6Sgx4SRnaFC2rwhxfjBw,deployType=REGULAR,envId=8ss-6DLmQeWe7EMejOVWEw,envName=deploy-open-sentinel-dev1,stageName=test-timeout,stageType=DEFAULT,deployStage=PRE_DOWNLOAD,build=<null>,deployAlias=<null>,agentConfigs={STOPPING.process_timeout=12000},scriptVariables=<null>,firstDeploy=false,isDocker=false]] for host dev-yaqinli.","timestamp":"2023-11-17T02:39:45.561+0000"}`
Deployd log:
```
2023-11-17 02:47:52,252 deployd.common.executor:54 DEBUG Executor configs have been updated: PING_INTERVAL=60, TIME_OUT=1800, MAX_RETRY=3
2023-11-17 02:47:52,252 deployd:444 INFO current deploy goal is: DeployGoal(deployId=8M6Sgx4SRnaFC2rwhxfjBw, envId=8ss-6DLmQeWe7EMejOVWEw, envName=deploy-open-sentinel-dev1, stageName=test-timeout, stageType=DEFAULT, deployStage=PRE_DOWNLOAD, build=None, deployAlias=None, agentConfig={'STOPPING.process_timeout': '12000'},scriptVariables=None, firstDeploy=False, isDocker=False)
```

**Review by ntascii — DISMISSED** [review]
can we update UTs or add new test for this change?

**Comment by liyaqin1** [comment]
> can we update UTs or add new test for this change?

Hi Anh, I tested via this new build on my devapp: https://github.com/pinterest/teletraan/pull/1345
https://deploy-dev1.pinadmin.com/env/deploy-open-sentinel-dev1/test-timeout/
Screenshot 2023-11-17 at 11 43 31 AM
And you can see the stage type DEFAULT is printed out as expected:
Screenshot 2023-11-17 at 11 35 32 AM

**Review by ntascii — APPROVED** [review]
lgtm

**Pull request merged**
