### PR TITLE
fix the s3 bucket name used for rollback history in prod

### PR DESCRIPTION
**Pull request by yongwen**

### CODE REVIEW

**Comment by michaelfu** [comment]
Was the bug because that the s3 bucket name didn't match the actual bucket name in S3?

**Comment by jinruh** [comment]
looks good.

**Comment by jinruh** [comment]
from the stack trace, it's likely previously it's due to the bucket name mismatch.

**Comment by yongwen** [comment]
@michaelfu the new deploy history code was looking for rollback history from s3 bucket with the prefix "ngapp-rollback-history" for prod, which would list the history from "ngapp-rollback-history-integ". we should use "ngapp-rollback-history-prod" instead. It was caused by a merge mistake from my side.

**Pull request merged**
