### PR TITLE
Filter base image help and host type help by cell

### PR DESCRIPTION
**Pull request by tylerwowen**
We should pass `cell` to requests since these 2 APIs are cell-aware.

### CODE REVIEW

**Comment by ntascii** [comment]
Just curious how you tested this change?

**Comment by tylerwowen** [comment]
> Just curious how you tested this change?

I have a dump of the integ DB and just applied to my local container so I was able to get to the cluster creation UI.

**Comment by ntascii** [comment]
Do we need to update this file as well https://sourcegraph.pinadmin.com/github.com/pinterest/teletraan/-/blob/deploy-board/deploy_board/templates/clusters/cluster_configuration.html?

**Comment by tylerwowen** [comment]
> Do we need to update this file as well https://sourcegraph.pinadmin.com/github.com/pinterest/teletraan/-/blob/deploy-board/deploy_board/templates/clusters/cluster_configuration.html?

Thanks, updated.

**Review by ntascii — APPROVED** [review]

**Pull request merged**
