### PR TITLE
put rodimus call to create the cluster at the end to avoid asg creation before teletraan env update

### PR DESCRIPTION
**Pull request by liyaqin1**
We send Rodimus request from Teletraan to create ASG even when the cluster creation is failed on Teletraan side.
So, when user tried to create it again, it always got the error like: the ASG exists.
We have to do all Teletraan side updates and then send Rodimus request to create ASG.

### CODE REVIEW

**Comment by tylerwowen** [comment]
I don't think there is a perfect order to fix the problem. We can still ran into situations that Teletraan has all information but ASG is missing in AWS. What we really need is _transaction_.

**Comment by liyaqin1** [comment]
> I don't think there is a perfect order to fix the problem. We can still ran into situations that Teletraan has all information but ASG is missing in AWS. What we really need is _transaction_.

I agree with you. This is a better way before we have transaction, right?
If the user failed in the steps before ASG creation, the users can delete the stage by themselves and then the issue will be solved.
If we have ASG created like in the current solution, we need to delete that on AWS side. And they also need to delete the stage.
If they forget to delete the stage and create the cluster again immediately, we have to delete the ASG again for them and at the same time delete the stage.

**Comment by liyaqin1** [comment]
tested on integ:
when I changed the stage type and then created the cluster, I got error like:
Screen Shot 2022-10-18 at 4 01 13 PM
And on AWS side, the ASG is not created which is expected:
Screen Shot 2022-10-18 at 4 10 33 PM

**Review by tylerwowen — APPROVED** [review]
Yeah it's fine for short term work around. Can you also include some Wiki instructions so users know what to expect and how to deal with any failures?

**Comment by liyaqin1** [comment]
> Yeah it's fine for short term work around. Can you also include some Wiki instructions so users know what to expect and how to deal with any failures?

Yes, I wrote a wiki and update the jira ticket with the wiki, thanks.

**Pull request merged**
