### PR TITLE
add the deploy operator name in the message

### PR DESCRIPTION
**Pull request by liyaqin1**

### CODE REVIEW

**Comment by liyaqin1** [comment]
tested locally ok.
I first configured the chatroom and then got the message successfully:
Screen Shot 2021-11-18 at 5 28 52 PM
Screen Shot 2021-11-18 at 5 29 36 PM

**Comment by robbintt** [comment]
What if it says `started by Anonymous.` in the first sentence?

**Comment by liyaqin1** [comment]
> What if it says `started by Anonymous.` in the first sentence?

it is because I am running it locally.
if deploying to integ, it could show the real operator name.

**Comment by ankilosaurus** [comment]
> > What if it says `started by Anonymous.` in the first sentence?
> 
> it is because I am running it locally. if deploying to integ, it could show the real operator name.

I think what @robbintt meant is change messaging to include operator name in first sentence.

**Review by ankilosaurus — APPROVED** [review]

**Comment by liyaqin1** [comment]
> > > What if it says `started by Anonymous.` in the first sentence?
> > 
> > 
> > it is because I am running it locally. if deploying to integ, it could show the real operator name.
> 
> I think what @robbintt meant is change messaging to include operator name in first sentence. Also, you might want to test this out in integ before merging to verify it shows real op.

Hey Ankit, I tested on integ ok and I will submit another pr to make sure the name is a link instead of the plain text. thanks.
Screen Shot 2021-11-19 at 6 42 02 PM

**Pull request merged**
