### PR TITLE
support json format in log

### PR DESCRIPTION
**Pull request by liyaqin1**
Bump dropwizard version and install some related dependencies to support json format in log message.

### CODE REVIEW

**Comment by robbintt** [comment]
What is the test plan for the dropwizard and dependencies? Have you read the changelog for all changes and tested those things?

**Comment by liyaqin1** [comment]
Here is the link for dropwizard release notes: https://www.dropwizard.io/en/latest/about/release-notes.html
We bumped the version from 0.8.1 to 1.3.0. ^^
Tested basic features on integ teletraan instance successfully.

There is also a minor change for backend api port which is used for devapp development locally.

**Comment by liyaqin1** [comment]
Some upgrade notes:
https://www.dropwizard.io/en/latest/manual/upgrade-notes/upgrade-notes-0_9_x.html
https://www.dropwizard.io/en/latest/manual/upgrade-notes/upgrade-notes-1_0_x.html
https://www.dropwizard.io/en/latest/manual/upgrade-notes/upgrade-notes-1_1_x.html
This google group says no breaking changes from 1.1 to 1.2:
https://groups.google.com/g/dropwizard-user/c/XQc-B2U2f3Y/m/vYFtSHu2AgAJ?pli=1
The last release is 1.3.29 instead of 1.3.0, so use that one to get all the security patches etc, rather than the initial release which is the first version supports json log.
https://github.com/dropwizard/dropwizard/tree/v1.3.29

**Comment by liyaqin1** [comment]
upgrade both teletraan and rodimus and tested basic features on integ already.

**Review by robbintt — APPROVED** [review]

**Review by tylerwowen — COMMENTED** [review]
This PR is approved.

**Pull request merged**
