### PR TITLE
optionally display STOPPING and STOPPED hosts

### PR DESCRIPTION
**Pull request by nathantypanski**
Previously, the environment overview page only showed hosts in the deploy
status that were not STOPPING or STOPPED. The only way to look at them is to
look in "Total" hosts.

First of all, it doesn't make sense to me to to have an agent state that shows
up in the TOTAL but isn't available in the board.

This adds an extra configuration parameter to display STOPPING and STOPPED
hosts. It is disabled by default, in case you have some reason you do not
display those states.

Related: #354

Current behavior:

screen shot 2017-03-15 at 9 24 35 pm

Notice the TOTAL for the *Previous(a2f66f1)* build is `1`, even though none of the state columns actually display 1 host!

With `os.environ.setdefault("DISPLAY_STOPPING_HOSTS", "true")` in `manage.py`, we can see even the stopped hosts:

screen shot 2017-03-15 at 9 24 59 pm

### CODE REVIEW

**Comment by lilida** [comment]
+@sbaogang for comment on STOPPING and STOPPED.

**Comment by sbaogang** [comment]
I am all for it - STOPPING/STOPPED was added as new features to gracefully terminate apps, apparently the UI part was not updated.

**Comment by nathantypanski** [comment]
Perhaps we should default it to enabled, then? Is there a reason to hide this?

**Comment by lilida** [comment]
I think it should be enabled by default, Nathan, can you make it be enabled?  Also, I'd like to have your agreement on distributing the code in Apache 2.0 license for me to merge it.  You can reply your agreement just here.

**Comment by nathantypanski** [comment]
I agree to have my code released under the Apache 2.0 license.

**Pull request merged**
